import platform
import sys

from urllib.parse import parse_qs, urlparse

import dicomsort

from dicomsort.gui.anonymizer import AnonymizeList
from dicomsort.gui.dialogs import (
    AboutDlg,
    CrashReporter,
    QuickRenameDialog,
    SeriesRemoveOptions,
    SeriesRemoveWarningDialog,
    UpdateDialog,
    webbrowser,
)
from tests.shared import WxTestCase


class TestCrashReporter(WxTestCase):
    def test_constructor(self):
        reporter = CrashReporter(self.frame)
        reporter.Destroy()

    def test_body(self):
        # Given an exception and a traceback
        try:
            raise AttributeError('oh no')
        except AttributeError:
            pass

        t, v, tb = sys.exc_info()

        # And a CrashReporter corresponding to this exception
        reporter = CrashReporter(self.frame, type=t, value=v, traceback=tb)

        # The body generated by the Crash Reporter
        body = reporter.body()

        # Has the expected information
        assert dicomsort.__version__ in body

        assert platform.system() in body
        assert platform.release() in body
        assert reporter.traceback() in body

    def test_on_file_issue(self, mocker):
        mock = mocker.patch.object(webbrowser, 'open')
        reporter = CrashReporter(self.frame)

        reporter.on_file_issue()

        assert mock.call_count == 1

        url = mock.call_args[0][0]

        parsed_url = urlparse(url)

        assert parsed_url.scheme == 'https'
        assert parsed_url.netloc == 'github.com'
        assert parsed_url.path == '/dicomsort/dicomsort/issues/new'

        query_params = parse_qs(parsed_url.query)

        assert 'body' in query_params
        assert query_params['body'][0] == reporter.body()


class TestUpdateDlg(WxTestCase):
    def test_on_update(self, mocker):
        dlg = UpdateDialog(self.frame, '1.2.3')
        url = dicomsort.Metadata.website

        mock = mocker.patch.object(dlg.hyperlink, 'GotoURL')

        dlg.on_update()

        mock.assert_called_once_with(url)


class TestAboutDialog(WxTestCase):
    def test_constructor(self):
        dlg = AboutDlg(self.frame)

        # Just a few sanity checks
        assert dlg.info.GetVersion() == dicomsort.__version__
        assert dlg.info.GetName() == 'DICOM Sort'
        assert dlg.info.GetWebSiteURL() == dicomsort.Metadata.website


class TestSeriesRemoveWarningDlg(WxTestCase):
    def test_on_original(self):
        dlg = SeriesRemoveWarningDialog(self.frame)
        dlg.on_button(None, SeriesRemoveOptions.ORIGINAL)
        dlg.Destroy()

        assert dlg.choice == SeriesRemoveOptions.ORIGINAL

    def test_on_cancel(self):
        dlg = SeriesRemoveWarningDialog(self.frame)
        dlg.on_button(None, SeriesRemoveOptions.CANCEL)
        dlg.Destroy()

        assert dlg.choice == SeriesRemoveOptions.CANCEL

    def test_on_custom(self):
        dlg = SeriesRemoveWarningDialog(self.frame)
        dlg.on_button(None, SeriesRemoveOptions.CUSTOM)
        dlg.Destroy()

        assert dlg.choice == SeriesRemoveOptions.CUSTOM


class TestQuickRenameDlg(WxTestCase):
    def test_no_patient_name_anonlist(self):
        a = AnonymizeList(self.frame)
        dlg = QuickRenameDialog(self.frame, anonList=a)

        expected = {
            'PatientName': '',
            'PatientID': '%(PatientName)s',
        }

        assert dlg.get_values() == expected

    def test_patient_name_anonlist(self):
        name = 'Patient0'
        a = AnonymizeList(self.frame)
        a.SetStringItems(['PatientName'])
        a.SetReplacementDict({'PatientName': name})

        dlg = QuickRenameDialog(self.frame, anonList=a)

        expected = {
            'PatientName': name,
            'PatientID': '%(PatientName)s',
        }

        assert dlg.get_values() == expected

    def test_on_accept(self):
        name = 'Patient0'
        a = AnonymizeList(self.frame)
        a.SetStringItems(['PatientName', 'PatientID'])
        a.SetReplacementDict({'PatientName': name, 'PatientID': 'ignored'})

        dlg = QuickRenameDialog(self.frame, anonList=a)

        dlg.on_accept()

        replacements = a.GetReplacementDict()

        assert replacements['PatientID'] == '%(PatientName)s'
        assert replacements['PatientName'] == name
