name: lint
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install Dependencies
        run: sudo pip install flake8

      - name: Perform Linting
        run: make lint
