name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install System Dependencies
        run: >
          sudo apt install --quiet libgtk-3-dev libnotify-dev libsdl2-dev &&
          sudo pip install wheel
          sudo pip install --progress-bar off -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/ wxpython==4.1.1 &&
          sudo pip install --progress-bar off -r requirements.txt &&
          sudo pip install -e .

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test suite
        run: make test
